# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
use_bioc: true
bioc_required: true
sudo: false
os:
  - linux
compiler:
  - gcc
  - clang
addons:
 apt:
   packages:
     - libudunits2-dev # required for units, required for ggforce, required for ggraph
     - libgdal-dev # required for sf
     - devscripts #required for configure/cleanup
env:
  global:
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
  # don't treat missing suggested packages as error
  - _R_CHECK_FORCE_SUGGESTS_=false
  # remove linux
  - TRAVIS_CXXFLAGS="-Wall -Wextra -pedantic -Werror"

r_packages:
  - phyloseq
  - data.table
  - parallel
  - utils
  - vegan
  - Rtsne
  - stringr
  - stats
  - grDevices
  - graphics
  - RColorBrewer
  - ggplot2
  - igraph
  - ggraph
  - ggrepel
  - sf
  - sp
  - rgdal
  - rgeos
  - Rcpp
  - RcppArmadillo

warnings_are_errors: false
