# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: false

addons:
 apt:
   packages:
     - libudunits2-dev # required for units, required for ggforce, required for ggraph
     - libgdal1-dev # required for sf