# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
use_bioc: true
bioc_required: true
cache:
  - packages
  - ccache
sudo: false
dist: trusty
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
addons:
 apt:
   packages:
     - libudunits2-dev # required for units, required for ggforce, required for ggraph
     - libgdal-dev # required for sf
env:
  global:
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
  # don't treat missing suggested packages as error
  - _R_CHECK_FORCE_SUGGESTS_=false
  # remove linux
  - TRAVIS_CXXFLAGS="-Wall -Wextra -pedantic -Werror"

r_binary_packages:
  - sp
  - ggplot2

# before_install:
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install llvm &&
#     export PATH="/usr/local/opt/llvm/bin:$PATH" &&
#     export LDFLAGS="-L/usr/local/opt/llvm/lib" &&
#     export CFLAGS="-I/usr/local/opt/llvm/include"; fi
